package com.bruno.conferente;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.webkit.*;import android.widget.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;import java.util.zip.*;import javax.xml.parsers.*;import org.w3c.dom.*;

public class MainActivity extends Activity {
 WebView web; DB db; int batchId=0; String mode="items"; int request=0; static final int REPORT=10, LOC=11, NEG=12, EXPORT=13; int selectedId=0;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff050b12);getWindow().setNavigationBarColor(0xff050b12);db=new DB(this);web=new WebView(this);web.setBackgroundColor(0xff07111b);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.addJavascriptInterface(new Bridge(),"Android");web.setWebViewClient(new WebViewClient());setContentView(web);web.loadUrl("file:///android_asset/index.html");}
 void js(String s){runOnUiThread(()->web.evaluateJavascript(s,null));}
 String esc(String s){return (s==null?"":s).replace("\\","\\\\").replace("'","\\'").replace("\n"," ").replace("\r"," ");}
 void picker(int r,String type,boolean create){request=r;Intent i=new Intent(create?Intent.ACTION_CREATE_DOCUMENT:Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(type);if(create)i.putExtra(Intent.EXTRA_TITLE,"faltando_conferencia.xlsx");startActivityForResult(i,r);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;Uri u=d.getData();try{if(r==REPORT) importReport(u); else if(r==LOC) importLocations(u); else if(r==NEG) importNegatives(u); else if(r==EXPORT) exportXlsx(u);}catch(Exception e){toast("Erro: "+e.getMessage(),false);}}
 void toast(String m,boolean ok){js("toastMsg('"+esc(m)+"',"+ok+")");}
 void importReport(Uri u)throws Exception{List<List<String>> rows=Xlsx.read(getContentResolver().openInputStream(u));int h=findHeader(rows,new String[]{"n.º de venda","n.o de venda","nome cliente","produto","título do anúncio","titulo do anuncio"});if(h<0)throw new Exception("Formato do relatório não reconhecido");Map<String,Integer> cols=map(rows.get(h));boolean ml=col(cols,"n.º de venda","n.o de venda")>=0;String name="Lista "+new SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date());batchId=db.newBatch(name);for(int i=h+1;i<rows.size();i++){List<String> r=rows.get(i);String order=val(r,cols,ml?new String[]{"n.º de venda","n.o de venda"}:new String[]{"pedido","número pedido"});String code=val(r,cols,ml?new String[]{"sku"}:new String[]{"código de barras","codigo de barras","ean","isbn"});String desc=val(r,cols,ml?new String[]{"título do anúncio","titulo do anuncio"}:new String[]{"produto","descrição","descricao"});if(code.isEmpty()||desc.isEmpty())continue;int qty=num(val(r,cols,new String[]{"unidades","quantidade","qtd"}),1);String buyer=val(r,cols,new String[]{"comprador","nome cliente"});String doc=val(r,cols,new String[]{"cpf","cpf/cnpj"});String tracking=val(r,cols,new String[]{"número de rastreamento","numero de rastreamento"});db.addItem(batchId,order,buyer,doc,ml?"Mercado Livre":"Pedidos",code,desc,qty,tracking);}db.applyCatalog(batchId);js("setBatch('"+esc(name)+"')");requestData();toast("Relatório importado com sucesso",true);}
 void importLocations(Uri u)throws Exception{List<List<String>> rows=Xlsx.read(getContentResolver().openInputStream(u));int h=findHeader(rows,new String[]{"localização ss","localizacao ss","localização simpleset","localizacao simpleset","código de barras","codigo de barras","isbn","ean"});if(h<0)h=0;Map<String,Integer> c=map(rows.get(h));int count=0;for(int i=h+1;i<rows.size();i++){List<String> r=rows.get(i);String code=val(r,c,new String[]{"código de barras","codigo de barras","isbn","ean","sku","código","codigo"});String loc=val(r,c,new String[]{"localização ss","localizacao ss","localização simpleset","localizacao simpleset","localização","localizacao"});if(!code.isEmpty()&&!loc.isEmpty()){db.putLocation(code,loc);count++;}}if(batchId>0)db.applyCatalog(batchId);requestData();toast(count+" localizações importadas",true);}
 void importNegatives(Uri u)throws Exception{List<List<String>> rows=Xlsx.read(getContentResolver().openInputStream(u));int h=findHeader(rows,new String[]{"código de barras","codigo de barras","ean","isbn","estoque","quantidade"});if(h<0)h=0;Map<String,Integer> c=map(rows.get(h));int n=0;for(int i=h+1;i<rows.size();i++){String code=val(rows.get(i),c,new String[]{"código de barras","codigo de barras","ean","isbn","sku","código","codigo"});String q=val(rows.get(i),c,new String[]{"estoque","quantidade","qtd"});if(!code.isEmpty()&&num(q,0)<0){db.markNegative(code,num(q,0));n++;}}toast(n+" itens negativos atualizados",true);requestData();}
 int findHeader(List<List<String>> rows,String[] keys){for(int i=0;i<Math.min(rows.size(),30);i++){String all=String.join("|",rows.get(i)).toLowerCase(Locale.ROOT);for(String k:keys)if(all.contains(k))return i;}return -1;}
 Map<String,Integer> map(List<String> h){Map<String,Integer> m=new HashMap<>();for(int i=0;i<h.size();i++)m.put(norm(h.get(i)),i);return m;}String norm(String s){return (s==null?"":java.text.Normalizer.normalize(s,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").trim().toLowerCase(Locale.ROOT));}int col(Map<String,Integer>m,String...ks){for(String k:ks){Integer x=m.get(norm(k));if(x!=null)return x;}return -1;}String val(List<String>r,Map<String,Integer>m,String[]ks){int i=col(m,ks);return i>=0&&i<r.size()?r.get(i).trim():"";}int num(String s,int d){try{return (int)Math.round(Double.parseDouble(s.replace(".","").replace(",",".")));}catch(Exception e){return d;}}
 void requestData(){if(batchId<=0){js("setData('[]');setSummary('{\"total\":0,\"checked\":0,\"missing\":0,\"excess\":0,\"percent\":0}')");return;}String arr=db.itemsJson(batchId);String sum=db.summaryJson(batchId);js("setData('"+esc(arr)+"');setSummary('"+esc(sum)+"')");}
 void exportXlsx(Uri u)throws Exception{List<String[]> rows=db.missingRows(batchId);Xlsx.write(getContentResolver().openOutputStream(u),rows);toast("Excel exportado com sucesso",true);}
 public class Bridge{
  @JavascriptInterface public void importReport(){picker(REPORT,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",false);}
  @JavascriptInterface public void importLocations(){picker(LOC,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",false);}
  @JavascriptInterface public void importNegatives(){picker(NEG,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",false);}
  @JavascriptInterface public void exportMissing(){if(batchId==0){toast("Selecione uma lista",false);return;}picker(EXPORT,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",true);}
  @JavascriptInterface public void requestData(){MainActivity.this.requestData();}
  @JavascriptInterface public void setMode(String m){mode=m;requestData();}
  @JavascriptInterface public void scan(String code,String m){if(batchId==0){toast("Importe ou selecione uma lista",false);return;}Map<String,String> r=m.equals("packages")?db.scanPackage(batchId,code):db.scanItem(batchId,code);String j="{\"ok\":"+r.get("ok")+",\"message\":\""+json(r.get("message"))+"\",\"code\":\""+json(code)+"\",\"time\":\""+new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date())+"\"}";js("scanResult('"+esc(j)+"')");}
  @JavascriptInterface public void newBatch(){runOnUiThread(()->{final EditText e=new EditText(MainActivity.this);e.setHint("Nome da lista");new AlertDialog.Builder(MainActivity.this).setTitle("Nova lista").setView(e).setPositiveButton("Criar",(d,w)->{batchId=db.newBatch(e.getText().toString().trim().isEmpty()?"Nova lista":e.getText().toString());js("setBatch('"+esc(db.batchName(batchId))+"')");requestData();}).setNegativeButton("Cancelar",null).show();});}
  @JavascriptInterface public void chooseBatch(){runOnUiThread(()->{List<Integer> ids=db.batchIds();List<String> names=db.batchNames();new AlertDialog.Builder(MainActivity.this).setTitle("Selecionar lista").setItems(names.toArray(new String[0]),(d,w)->{batchId=ids.get(w);js("setBatch('"+esc(names.get(w))+"')");requestData();}).show();});}
  @JavascriptInterface public void renameBatch(){if(batchId==0)return;runOnUiThread(()->{EditText e=new EditText(MainActivity.this);e.setText(db.batchName(batchId));new AlertDialog.Builder(MainActivity.this).setTitle("Renomear lista").setView(e).setPositiveButton("Salvar",(d,w)->{db.renameBatch(batchId,e.getText().toString());js("setBatch('"+esc(e.getText().toString())+"')");}).setNegativeButton("Cancelar",null).show();});}
  @JavascriptInterface public void deleteBatch(){if(batchId==0)return;runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Excluir lista?").setMessage("A lista e sua conferência serão removidas.").setPositiveButton("Excluir",(d,w)->{db.deleteBatch(batchId);batchId=0;js("setBatch('Selecione uma lista')");requestData();}).setNegativeButton("Cancelar",null).show());}
  @JavascriptInterface public void undoScan(){if(batchId>0){db.undo(batchId);requestData();toast("Última conferência desfeita",true);}}
  @JavascriptInterface public void refreshLocations(){if(batchId>0){db.applyCatalog(batchId);requestData();toast("Localizações atualizadas",true);}}
  @JavascriptInterface public void selectItem(int id){selectedId=id;String code=db.codeOf(id);String url=code.length()==13?"https://covers.openlibrary.org/b/isbn/"+code+"-L.jpg":"";js("setCover('"+esc(url)+"')");}
  @JavascriptInterface public void openCover(){searchWeb();}
  @JavascriptInterface public void searchWeb(){if(selectedId==0)return;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?tbm=isch&q="+URLEncoder.encode(db.codeOf(selectedId),"UTF-8"))));}catch(Exception e){}}
  @JavascriptInterface public void coverSearch(){toast("Selecione um item para pesquisar a capa",true);}
  @JavascriptInterface public void soundSettings(){toast("Sons de conferência ativos",true);}
  @JavascriptInterface public void printMissing(){toast("Use Exportar relatório para gerar a lista de faltantes",true);}
  @JavascriptInterface public void about(){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Conferente Pedidos Online").setMessage("Versão V31 Android Nativo\nConferência de itens e pacotes").setPositiveButton("OK",null).show());}
 }
 static String json(String s){return (s==null?"":s).replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ").replace("\r"," ");}
 static class DB extends SQLiteOpenHelper{
  DB(Context c){super(c,"conferente_v31.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE batches(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,created TEXT DEFAULT CURRENT_TIMESTAMP)");d.execSQL("CREATE TABLE items(id INTEGER PRIMARY KEY AUTOINCREMENT,batch_id INTEGER,order_id TEXT,buyer TEXT,doc TEXT,platform TEXT,code TEXT,description TEXT,qty INTEGER,checked INTEGER DEFAULT 0,location TEXT DEFAULT '',negative INTEGER DEFAULT 0,tracking TEXT DEFAULT '')");d.execSQL("CREATE TABLE locations(code TEXT PRIMARY KEY,location TEXT)");d.execSQL("CREATE TABLE packages(id INTEGER PRIMARY KEY AUTOINCREMENT,batch_id INTEGER,tracking TEXT,key TEXT,checked INTEGER DEFAULT 0,UNIQUE(batch_id,key))");d.execSQL("CREATE TABLE history(id INTEGER PRIMARY KEY AUTOINCREMENT,batch_id INTEGER,item_id INTEGER,kind TEXT,created TEXT DEFAULT CURRENT_TIMESTAMP)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}
  int newBatch(String n){ContentValues v=new ContentValues();v.put("name",n);return (int)getWritableDatabase().insert("batches",null,v);}String batchName(int id){Cursor c=getReadableDatabase().rawQuery("SELECT name FROM batches WHERE id=?",new String[]{""+id});String s="";if(c.moveToFirst())s=c.getString(0);c.close();return s;}List<Integer> batchIds(){List<Integer>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id FROM batches ORDER BY id DESC",null);while(c.moveToNext())a.add(c.getInt(0));c.close();return a;}List<String> batchNames(){List<String>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT name FROM batches ORDER BY id DESC",null);while(c.moveToNext())a.add(c.getString(0));c.close();return a;}void renameBatch(int id,String n){ContentValues v=new ContentValues();v.put("name",n);getWritableDatabase().update("batches",v,"id=?",new String[]{""+id});}void deleteBatch(int id){SQLiteDatabase d=getWritableDatabase();d.delete("items","batch_id=?",new String[]{""+id});d.delete("packages","batch_id=?",new String[]{""+id});d.delete("batches","id=?",new String[]{""+id});}
  void addItem(int b,String o,String buyer,String doc,String platform,String code,String desc,int qty,String tracking){SQLiteDatabase d=getWritableDatabase();ContentValues v=new ContentValues();v.put("batch_id",b);v.put("order_id",o);v.put("buyer",buyer);v.put("doc",doc);v.put("platform",platform);v.put("code",code);v.put("description",desc);v.put("qty",qty);v.put("tracking",tracking);d.insert("items",null,v);String k=trackKey(tracking);if(!k.isEmpty()){ContentValues p=new ContentValues();p.put("batch_id",b);p.put("tracking",tracking);p.put("key",k);d.insertWithOnConflict("packages",null,p,SQLiteDatabase.CONFLICT_IGNORE);}}
  static String trackKey(String s){if(s==null)return"";java.util.regex.Matcher m=java.util.regex.Pattern.compile("(\\d{11})").matcher(s.replaceAll("\\s","").toUpperCase());return m.find()?m.group(1):"";}
  void putLocation(String c,String l){ContentValues v=new ContentValues();v.put("code",c);v.put("location",l);getWritableDatabase().insertWithOnConflict("locations",null,v,SQLiteDatabase.CONFLICT_REPLACE);}void applyCatalog(int b){getWritableDatabase().execSQL("UPDATE items SET location=COALESCE((SELECT location FROM locations WHERE locations.code=items.code),'') WHERE batch_id=?",new Object[]{b});}void markNegative(String code,int q){getWritableDatabase().execSQL("UPDATE items SET negative=? WHERE code=?",new Object[]{q,code});}
  Map<String,String> scanItem(int b,String code){Map<String,String>r=new HashMap<>();SQLiteDatabase d=getWritableDatabase();Cursor c=d.rawQuery("SELECT id,qty,checked FROM items WHERE batch_id=? AND code=? AND checked<qty ORDER BY id LIMIT 1",new String[]{""+b,code});if(c.moveToFirst()){int id=c.getInt(0),q=c.getInt(1),ch=c.getInt(2)+1;d.execSQL("UPDATE items SET checked=? WHERE id=?",new Object[]{ch,id});d.execSQL("INSERT INTO history(batch_id,item_id,kind) VALUES(?,?,'item')",new Object[]{b,id});r.put("ok","true");r.put("message",ch>=q?"Item conferido":"Bip registrado: "+ch+"/"+q);}else{Cursor x=d.rawQuery("SELECT id FROM items WHERE batch_id=? AND code=?",new String[]{""+b,code});boolean exists=x.moveToFirst();x.close();r.put("ok","false");r.put("message",exists?"Quantidade já conferida":"Código não encontrado");}c.close();return r;}
  Map<String,String> scanPackage(int b,String code){Map<String,String>r=new HashMap<>();String k=trackKey(code);if(k.isEmpty()){r.put("ok","false");r.put("message","Rastreio inválido");return r;}SQLiteDatabase d=getWritableDatabase();Cursor c=d.rawQuery("SELECT id,checked FROM packages WHERE batch_id=? AND key=?",new String[]{""+b,k});if(!c.moveToFirst()){r.put("ok","false");r.put("message","Pacote não encontrado");}else if(c.getInt(1)>0){r.put("ok","false");r.put("message","Pacote já conferido");}else{int id=c.getInt(0);d.execSQL("UPDATE packages SET checked=1 WHERE id=?",new Object[]{id});d.execSQL("INSERT INTO history(batch_id,item_id,kind) VALUES(?,?,'package')",new Object[]{b,id});r.put("ok","true");r.put("message","Pacote conferido");}c.close();return r;}
  void undo(int b){SQLiteDatabase d=getWritableDatabase();Cursor c=d.rawQuery("SELECT id,item_id,kind FROM history WHERE batch_id=? ORDER BY id DESC LIMIT 1",new String[]{""+b});if(c.moveToFirst()){int hid=c.getInt(0),id=c.getInt(1);String k=c.getString(2);if(k.equals("item"))d.execSQL("UPDATE items SET checked=CASE WHEN checked>0 THEN checked-1 ELSE 0 END WHERE id=?",new Object[]{id});else d.execSQL("UPDATE packages SET checked=0 WHERE id=?",new Object[]{id});d.delete("history","id=?",new String[]{""+hid});}c.close();}
  String itemsJson(int b){StringBuilder s=new StringBuilder("[");Cursor c=getReadableDatabase().rawQuery("SELECT id,order_id,buyer,platform,code,description,qty,checked,location FROM items WHERE batch_id=? ORDER BY id",new String[]{""+b});boolean first=true;while(c.moveToNext()){if(!first)s.append(',');first=false;int q=c.getInt(6),ch=c.getInt(7);s.append("{\"id\":").append(c.getInt(0)).append(",\"order\":\"").append(json(c.getString(1))).append("\",\"buyer\":\"").append(json(c.getString(2))).append("\",\"platform\":\"").append(json(c.getString(3))).append("\",\"code\":\"").append(json(c.getString(4))).append("\",\"description\":\"").append(json(c.getString(5))).append("\",\"qty\":").append(q).append(",\"checked\":").append(ch).append(",\"missing\":").append(Math.max(0,q-ch)).append(",\"location\":\"").append(json(c.getString(8))).append("\"}");}c.close();return s.append(']').toString();}
  String summaryJson(int b){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(qty),0),COALESCE(SUM(MIN(qty,checked)),0),COALESCE(SUM(MAX(qty-checked,0)),0),COALESCE(SUM(MAX(checked-qty,0)),0) FROM items WHERE batch_id=?",new String[]{""+b});c.moveToFirst();int t=c.getInt(0),ch=c.getInt(1),m=c.getInt(2),e=c.getInt(3);c.close();int p=t==0?0:(int)Math.round(ch*100.0/t);return "{\"total\":"+t+",\"checked\":"+ch+",\"missing\":"+m+",\"excess\":"+e+",\"percent\":"+p+"}";}
  List<String[]> missingRows(int b){List<String[]>a=new ArrayList<>();a.add(new String[]{"Código de Barras","Descrição","Quantidade Faltando","Localização SS"});Cursor c=getReadableDatabase().rawQuery("SELECT code,description,qty-checked,location FROM items WHERE batch_id=? AND checked<qty",new String[]{""+b});while(c.moveToNext())a.add(new String[]{c.getString(0),c.getString(1),""+c.getInt(2),c.getString(3)});c.close();return a;}String codeOf(int id){Cursor c=getReadableDatabase().rawQuery("SELECT code FROM items WHERE id=?",new String[]{""+id});String s="";if(c.moveToFirst())s=c.getString(0);c.close();return s;}
 }
 static class Xlsx{
  static List<List<String>> read(InputStream in)throws Exception{Map<String,byte[]> z=new HashMap<>();ZipInputStream zi=new ZipInputStream(in);ZipEntry e;while((e=zi.getNextEntry())!=null){ByteArrayOutputStream b=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=zi.read(buf))>0)b.write(buf,0,n);z.put(e.getName(),b.toByteArray());}List<String> shared=new ArrayList<>();byte[]ss=z.get("xl/sharedStrings.xml");if(ss!=null){Document d=parse(ss);NodeList ts=d.getElementsByTagName("t");for(int i=0;i<ts.getLength();i++)shared.add(ts.item(i).getTextContent());}byte[]sh=z.get("xl/worksheets/sheet1.xml");if(sh==null)throw new Exception("Planilha sem primeira aba");Document d=parse(sh);NodeList rs=d.getElementsByTagName("row");List<List<String>> out=new ArrayList<>();for(int i=0;i<rs.getLength();i++){Element row=(Element)rs.item(i);NodeList cs=row.getElementsByTagName("c");List<String> vals=new ArrayList<>();for(int j=0;j<cs.getLength();j++){Element c=(Element)cs.item(j);String ref=c.getAttribute("r");int idx=colIndex(ref);while(vals.size()<=idx)vals.add("");String t=c.getAttribute("t"),v="";NodeList vs=c.getElementsByTagName("v");if(vs.getLength()>0)v=vs.item(0).getTextContent();else{NodeList is=c.getElementsByTagName("t");if(is.getLength()>0)v=is.item(0).getTextContent();}if(t.equals("s")&&!v.isEmpty()){int x=Integer.parseInt(v);v=x<shared.size()?shared.get(x):v;}vals.set(idx,v);}out.add(vals);}return out;}
  static Document parse(byte[]b)throws Exception{DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();f.setNamespaceAware(false);return f.newDocumentBuilder().parse(new ByteArrayInputStream(b));}static int colIndex(String r){int n=0;for(char c:r.toCharArray()){if(!Character.isLetter(c))break;n=n*26+(Character.toUpperCase(c)-'A'+1);}return Math.max(0,n-1);}
  static void write(OutputStream out,List<String[]> rows)throws Exception{ZipOutputStream z=new ZipOutputStream(out);put(z,"[Content_Types].xml","<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");put(z,"_rels/.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");put(z,"xl/workbook.xml","<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Faltando\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");put(z,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");StringBuilder s=new StringBuilder("<?xml version=\"1.0\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");for(int r=0;r<rows.size();r++){s.append("<row r=\"").append(r+1).append("\">");for(int c=0;c<rows.get(r).length;c++){String ref=letters(c+1)+(r+1);s.append("<c r=\"").append(ref).append("\" t=\"inlineStr\"><is><t>").append(xml(rows.get(r)[c])).append("</t></is></c>");}s.append("</row>");}s.append("</sheetData></worksheet>");put(z,"xl/worksheets/sheet1.xml",s.toString());z.finish();z.close();}
  static void put(ZipOutputStream z,String n,String s)throws Exception{z.putNextEntry(new ZipEntry(n));z.write(s.getBytes("UTF-8"));z.closeEntry();}static String xml(String s){return(s==null?"":s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}static String letters(int n){String s="";while(n>0){n--;s=(char)('A'+n%26)+s;n/=26;}return s;}
 }
}
