plugins { id 'com.android.application' }

android { namespace 'com.bruno.conferente'; compileSdk 35
    defaultConfig { applicationId 'com.bruno.conferente'; minSdk 26; targetSdk 35; versionCode 37; versionName '31.3.3' }
}


dependencies {
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
}
