name: Gerar APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Preparar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Preparar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 \
          cmake libffi-dev libssl-dev

      - name: Verificar ambiente
        run: |
          python --version
          git --version
          java -version
          which python
          which git
          which java

      - name: Instalar Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython==0.29.36

      - name: Limpar compilacao anterior
        run: |
          rm -rf .buildozer

      - name: Gerar APK
        run: |
          python --version
          git --version

          buildozer android debug || true

          VENV=".buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/venv"

          if [ -d "$VENV" ]; then
            echo "Corrigindo ambiente interno do pip..."
            rm -rf "$VENV"
          fi

          buildozer android debug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Conferente-Pedidos-Android
          path: bin/*.apk
          if-no-files-found: error
